{% set repo_name = "whitebox-tools" %}
{% set name = "whitebox_tools" %}
{% set version = "0.7" %} # version number is also hardcoded in setup.py
{% set sha256 = "1a5b80b6f0fffaae67aa8d22e0c8696f4d8368365a0962d5436395e93eb7bb80" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: go-spatial_darwin_amd64.zip  # [osx]
  url: http://www.uoguelph.ca/~hydrogeo/WhiteboxTools/WhiteboxTools_darwin_amd64.zip  # [osx]
  sha256: "5560e0395dc3604897e95516a2a01928cbd5dc23a3480342a7f466f7a0564a00"  # [osx]
  fn: WhiteboxTools_linux_amd64.tar.xz  # [linux]
  url: http://www.uoguelph.ca/~hydrogeo/WhiteboxTools/WhiteboxTools_linux_amd64.tar.xz  # [linux]
  sha256: "cf3e81ef6103b28fac6b4e88e83b4262977a4005c951053d228e0a785f0d098b"  # [linux]
  fn: WhiteboxTools_win_amd64.zip  # [win]
  url: http://www.uoguelph.ca/~hydrogeo/WhiteboxTools/WhiteboxTools_win_amd64.zip  # [win]
  sha256: "4e0b6749b49ede34b5065289f19ce85adccac1ed00c1895f6ad988ae7468ee0b"  # [win]
  patches:
    - wbt.patch

build:
  number: 0
  skip: True  # [py2k]

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - whitebox_tools
  commands:
    - whitebox_tools --help  # [not win]
    - whitebox_tools.exe --help  # [win]

about:
  home: https://github.com/jblindsay/whitebox-tools
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Whitebox Tools is a collection of advanced geospatial data analysis tools.'
  description: |
    WhiteboxTools is an advanced geospatial data analysis platform developed by Prof. John Lindsay at 
    the University of Guelph's Geomorphometry and Hydrogeomatics Research Group. WhiteboxTools can be 
    used to perform common geographical information systems (GIS) analysis operations, such as 
    cost-distance analysis, distance buffering, and raster reclassification. Remote sensing and image 
    processing tasks include image enhancement (e.g. panchromatic sharpening, contrast adjustments), 
    image mosaicing, numerous filtering operations, simple classification (k-means), and common image 
    transformations. WhiteboxTools also contains advanced tooling for spatial hydrological analysis 
    (e.g. flow-accumulation, watershed delineation, stream network analysis, sink removal), terrain 
    analysis (e.g. common terrain indices such as slope, curvatures, wetness index, hillshading; 
    hypsometric analysis; multi-scale topographic position analysis), and LiDAR data processing. LiDAR 
    point clouds can be interrogated (LidarInfo, LidarHistogram), segmented, tiled and joined, 
    analyized for outliers, interpolated to rasters (DEMs, intensity images), and ground-points can be 
    classified or filtered. WhiteboxTools is not a cartographic or spatial data visualization package; 
    instead it is meant to serve as an analytical backend for other data visualization software, 
    mainly GIS.

extra:
  recipe-maintainers:
    - dharhas
    - sdc50
