{% set name = "whitebox_tools" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jblindsay/whitebox-tools/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b7715731e1519be71cf1d05d1d1f93c36d498c218da0a898bab95e16dd403a8e

build:
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - python
  imports:
    - whitebox_tools
  commands:
    - whitebox_tools --help  # [not win]
    - whitebox_tools.exe --help  # [win]
    - python -c "import whitebox_tools"

about:
  home: https://github.com/jblindsay/whitebox-tools
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml

  summary: Whitebox Tools is a collection of advanced geospatial data analysis tools.
  description: |
    WhiteboxTools is an advanced geospatial data analysis platform developed by Prof. John Lindsay at
    the University of Guelph's Geomorphometry and Hydrogeomatics Research Group. WhiteboxTools can be
    used to perform common geographical information systems (GIS) analysis operations, such as
    cost-distance analysis, distance buffering, and raster reclassification. Remote sensing and image
    processing tasks include image enhancement (e.g. panchromatic sharpening, contrast adjustments),
    image mosaicing, numerous filtering operations, simple classification (k-means), and common image
    transformations. WhiteboxTools also contains advanced tooling for spatial hydrological analysis
    (e.g. flow-accumulation, watershed delineation, stream network analysis, sink removal), terrain
    analysis (e.g. common terrain indices such as slope, curvatures, wetness index, hillshading;
    hypsometric analysis; multi-scale topographic position analysis), and LiDAR data processing. LiDAR
    point clouds can be interrogated (LidarInfo, LidarHistogram), segmented, tiled and joined,
    analyized for outliers, interpolated to rasters (DEMs, intensity images), and ground-points can be
    classified or filtered. WhiteboxTools is not a cartographic or spatial data visualization package;
    instead it is meant to serve as an analytical backend for other data visualization software,
    mainly GIS.

extra:
  recipe-maintainers:
    - dharhas
    - sdc50
    - hobu
