travis:
  secure:
    BINSTAR_TOKEN: CZYKhvgcuJlScjFjzfdJMZJY8SmgAemUZT6MlYPqspkwW+9jcG6Pluuh335ZfaZbigVs5n2VQTPWQ2dlC3G6GD2NF3Sfyq0o1MHeWFnghFf4izdCN6TcDTD25JSeJ+BbudPb7tuiztmlufzTp/zuPy3DXjPgooEw2mjOotA6EUjsFKAeS9lYDjBDzZUe/7CIA5Y7vSV98ci29NySQTDcyYCbV5Ni27+MyzClKHJZdhomrwzDZD9T6VbUglW8d8ssYaPXafe3cVw+K5hAmfH5xdX+tENXhQHq0MhypICgjj78O6kpQNJsu1oirN7Zj+I0G82tEPTwMAvFkneeTh0wA5YDieD3RWEoTZwKNOI+VTf6dwU6wo/C1Y2KHpAJhwJ715q8kBXhcdA7fbA+d6XEfbSKRo4K/4XxEivy23THbcYT1gdbNyK1TJAb6qEtnobEuR32mR5NeQ8MjUca15LbGviCaMc6g2laL3Pm2C0OJHJB9BpHEk/+gdCaWfhXit/BibNOcs3aItgMcoX1l3tqiMVC1py3P0p4hz5ybhtsWJkj825UQqVsmlQg6hKMQ1nKgAMNMPoYokcecTn9q3YKrx3NlXLgtHxXLv0H2DM/RvEAsMUvGN7TpPqBHLwhCoyMjI3QQIzHrijSmIPJj/pEHy5tmmsBHvlWa2mfQ9I0Mcs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
