appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: OGlRJ5+TXgprI8i6GHvWICwmI633azNIuD6g9PWp1mrJKyJlRO16NiIO1dZmjT6N3wPfUYQnj2Yf0t0c7eYqtL/WybhLfuI4Y1QzRVfK4QJ5+siqxo0VHpIgyRNHhoma22h/pzBfqOSHqtT2pwlhhxk9L8CCEK6yFdCk2wABnjuYF39i/kZy2444/Nyrws62OHAAPLEwS6PFpmV4lbsSPBKjYtsV/yM5vbU8CEQTpJPfKsVtlliE22BKxQuZCsN0JbEXKZduxmGNaHEPzsIfHO7nwV7kVuQy4LtfvZpR19OA6SzZ5+UlS1kBHzu3HOoZYTATex9ZZfRaPlPUlDS7fSFxJyo5jNhso1XagyVrmn0/1eanG6Kvq5nGvWndLhGEBZ5MtxWjUg1/DKDclWCwuz2DqiMjXUiftrTDZPij+e3LDmVUIcpiGwztsUy3mzX0q1czKBmjWhXSDIy5uU3HLcUh/9IZXS4K+whcrM/z+2UONpU+/U/lmxC/yddI0SI8iQMKdO3XuFnMrDLfUJu+RAjEqA4yH1tLzVBMOqccRQPR1n3wTZsyGMHbF4pArFbQhvint2JOIk+/nj8jULHAdv1wtdbih9/PL/5UHwV3+8954UR9Cguk2DmxbGzmX0sPnt0oOA0askn5q+oo/gQEeZ5um+DmJy5Lots7H4GP65I=}
