travis:
  secure:
    BINSTAR_TOKEN: YSgWcx0B9CMJ+tKKbNM8obQx0O266sd6cvGD5EoWyakNMeCi/5FQg2FmocOsb+o+Jrr/ymBobWyPuNMcj+6BV/CI7P4V924RA/niddZ3OkGhKzlnUQDtHDBedPvw3+RW/kn7LkPptLBEd4NosICLshX6L4DpzZkHYzAT8qCAml/HeuMefbHBmh9Cai+80MIVpD2HmqSFoajZDk0vLXhrtMAB7EOt7eqS2DxB0Oa5DTk4utoJ7Mpd+/11tLfP17xy17+OEZam46Zxuwzwn4+J7ReuTag4aqEB3PgHAkygWSom3n+mQepxA18Jfc6ZUTgShqxErQMIW+dA0RRJP+AxZ18bU3U30OCbHyDzcBJsI2YR2LZqIytrDYIpF89iA5HpdG5wnG2QkYPvZ6+vAfY6qW0jX6I60ESPYBRwhmJBvwR3QiJv0Cxx2n20VBPtc9l9+7/bkDPT2I/ZFcyELcueex8GCSFt6rvFEinhMeNyIA/ThGLsyD7IXz/6rdqav37rnioF5N5PefZpWQx4kjqlWQ8o/FsFrzn1eDe8ibNwCK/V7t9xWlchqdq5csgloQfVnAW3FYW8ETpNpiGmGEPnuE9XEjtoHAq01oUenxM+Jtxf8OY+PMEf9vBsRy8/hPP+bqGvhRFxu2/tpztHWekGf9zrIrVbj1BtAaEXhQy6W/g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
